package com.tesseract.demo.Service;

import java.io.IOException;
import java.time.LocalDate;

import org.hibernate.engine.jdbc.BlobProxy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;
import org.springframework.core.io.Resource;
import org.springframework.security.crypto.password.PasswordEncoder;

import com.tesseract.demo.Model.Collection;
import com.tesseract.demo.Model.Flashcard;
import com.tesseract.demo.Model.Text;
import com.tesseract.demo.Model.User;
import com.tesseract.demo.Model.Word;

import jakarta.annotation.PostConstruct;


@Service
public class DatabaseInitializer {
    
    @Autowired
    DictionaryService dictionaryService;

    @Autowired
    TextService textService;

    @Autowired
    CollectionService collectionService;

    @Autowired
    FlashcardService flashcardService;

    @Autowired
    UserService userService;

    @Autowired
	private PasswordEncoder passwordEncoder;

    @PostConstruct
    public void initializeDatabase(){
        Word[] words = new Word[] {
            new Word("我", "wǒ", "I; Me", "Yo"),
            new Word("你", "nǐ", "You", "Tú"),
            new Word("他", "tā", "He", "Él"),
            new Word("她", "tā", "She", "Ella"),
            new Word("我们", "wǒmen", "We", "Nosotros"),
            new Word("你们", "nǐmen", "You (plural)", "Vosotros"),
            new Word("他们", "tāmen", "They (male or mixed)", "Ellos"),
            new Word("她们", "tāmen", "They (female)", "Ellas"),
            new Word("你好", "nǐ hǎo", "Hello", "Hola"),
            new Word("中国", "Zhōngguó", "China", "China"),
            new Word("中文", "Zhōngwén", "Chinese language", "Idioma chino"),
            new Word("汉语", "Hànyǔ", "Chinese language", "Idioma chino"),
            new Word("朋友", "péngyǒu", "Friend", "Amigo"),
            new Word("很", "hěn", "Very", "Muy"),
            new Word("好", "hǎo", "Good; Well", "Bien"),
            new Word("有", "yǒu", "To have", "Tener"),
            new Word("喜欢", "xǐhuān", "To like", "Gustar"),
            new Word("菜", "cài", "Food; Dish", "Comida"),
            new Word("一", "yī", "One", "Uno"),
            new Word("个", "gè", "Classifier for things in general", "Clasificador para objetos en general"),
            new Word("的", "de", "Indicates possession; also used in shi de construction; turns verbs/adjectives into nouns", "Partícula que indica posesión; Usado en la construcción para indicar pasado; Describe sustantivos y convierte verbos o adjetivos en sustantivos"),
            new Word("祝", "zhù", "To wish", "Desear"),
            new Word("幸福", "xìngfú", "Happiness", "Felicidad"),
            new Word("住", "zhù", "To live", "Vivir"),
            new Word("马德里", "Mǎdélǐ", "Madrid (capital of Spain)", "Madrid (capital de España)"),
            new Word("在", "zài", "To be in; Located at", "(Estar) en"),
            new Word("里", "lǐ", "Inside", "En; Dentro de"),
            new Word("是", "shì", "To be", "Ser"),
            new Word("了", "le", "Marks a completed action or change", "Partícula que indica un cambio en una situación o una acción completada"),
            new Word("学习", "xuéxí", "To study", "Estudiar"),
            new Word("学校", "xuéxiào", "School", "Escuela"),
            new Word("老师", "lǎoshī", "Teacher", "Profesor"),
            new Word("学生", "xuéshēng", "Student", "Estudiante"),
            new Word("语言", "yǔyán", "Language", "Lengua"),
            new Word("书", "shū", "Book", "Libro"),
            new Word("桌子", "zhuōzi", "Table", "Mesa"),
            new Word("水", "shuǐ", "Water", "Agua"),
            new Word("茶", "chá", "Tea", "Té"),
            new Word("咖啡", "kāfēi", "Coffee", "Café"),
            new Word("牛奶", "niúnǎi", "Milk", "Leche"),
            new Word("苹果", "píngguǒ", "Apple", "Manzana"),
            new Word("香蕉", "xiāngjiāo", "Banana", "Banana"),
            new Word("米饭", "mǐfàn", "Cooked rice", "Arroz cocido"),
            new Word("面条", "miàntiáo", "Noodles", "Fideos"),
            new Word("鱼", "yú", "Fish", "Pescado"),
            new Word("肉", "ròu", "Meat", "Carne"),
            new Word("鸡", "jī", "Chicken", "Pollo"),
            new Word("猪", "zhū", "Pig", "Cerdo"),
            new Word("家", "jiā", "Home; Family", "Casa; Familia"),
            new Word("房子", "fángzi", "House", "Casa"),
            new Word("门", "mén", "Door", "Puerta"),
            new Word("窗户", "chuānghu", "Window", "Ventana"),
            new Word("床", "chuáng", "Bed", "Cama"),
            new Word("衣服", "yīfu", "Clothes", "Ropa"),
            new Word("鞋子", "xiézi", "Shoes", "Zapatos"),
            new Word("裤子", "kùzi", "Pants", "Pantalones"),
            new Word("衣柜", "yīguì", "Wardrobe", "Armario"),
            new Word("车", "chē", "Car; Vehicle", "Coche; Vehículo"),
            new Word("自行车", "zìxíngchē", "Bicycle", "Bicicleta"),
            new Word("飞机", "fēijī", "Airplane", "Avión"),
            new Word("火车", "huǒchē", "Train", "Tren"),
            new Word("船", "chuán", "Boat; Ship", "Barco; Nave"),
            new Word("路", "lù", "Road; Path", "Camino; Carretera"),
            new Word("街", "jiē", "Street", "Calle"),
            new Word("商店", "shāngdiàn", "Shop; Store", "Tienda"),
            new Word("饭店", "fàndiàn", "Restaurant; Hotel", "Restaurante; Hotel"),
            new Word("银行", "yínháng", "Bank", "Banco"),
            new Word("教室", "jiàoshì", "Classroom", "Aula"),
            new Word("图书馆", "túshūguǎn", "Library", "Biblioteca"),
            new Word("电影院", "diànyǐngyuàn", "Cinema; Movie Theater", "Cine"),
            new Word("电影", "diànyǐng", "Movie; Film", "Película"),
            new Word("音乐", "yīnyuè", "Music", "Música"),
            new Word("歌", "gē", "Song", "Canción"),
            new Word("跳舞", "tiàowǔ", "To dance", "Bailar"),
            new Word("唱歌", "chànggē", "To sing", "Cantar"),
            new Word("运动", "yùndòng", "Sport; Exercise", "Deporte; Ejercicio"),
            new Word("足球", "zúqiú", "Football (soccer)", "Fútbol"),
            new Word("篮球", "lánqiú", "Basketball", "Baloncesto"),
            new Word("跑步", "pǎobù", "To run", "Correr"),
            new Word("游泳", "yóuyǒng", "To swim", "Nadar"),
            new Word("工作", "gōngzuò", "Work; Job", "Trabajo; Empleo"),
            new Word("护士", "hùshì", "Nurse", "Enfermera"),
            new Word("警察", "jǐngchá", "Police officer", "Policía"),
            new Word("司机", "sījī", "Driver", "Conductor"),
            new Word("老板", "lǎobǎn", "Boss; Owner", "Jefe; Dueño"),
            new Word("家人", "jiārén", "Family members", "Familiares"),
            new Word("爸爸", "bàba", "Dad; Father", "Papá"),
            new Word("妈妈", "māma", "Mom; Mother", "Mamá"),
            new Word("哥哥", "gēge", "Older brother", "Hermano mayor"),
            new Word("姐姐", "jiějie", "Older sister", "Hermana mayor"),
            new Word("弟弟", "dìdi", "Younger brother", "Hermano menor"),
            new Word("妹妹", "mèimei", "Younger sister", "Hermana menor"),
            new Word("小时", "xiǎoshí", "Hour", "Hora"),
            new Word("分钟", "fēnzhōng", "Minute", "Minuto"),
            new Word("秒", "miǎo", "Second", "Segundo"),
            new Word("今天", "jīntiān", "Today", "Hoy"),
            new Word("昨天", "zuótiān", "Yesterday", "Ayer"),
            new Word("明天", "míngtiān", "Tomorrow", "Mañana"),
            new Word("早上", "zǎoshang", "Morning", "Mañana (temprano)"),
            new Word("下午", "xiàwǔ", "Afternoon", "Tarde"),
            new Word("晚上", "wǎnshang", "Evening; Night", "Noche"),
            new Word("星期", "xīngqī", "Week", "Semana"),
            new Word("月", "yuè", "Month", "Mes"),
            new Word("年", "nián", "Year", "Año"),
            new Word("春天", "chūntiān", "Spring", "Primavera"),
            new Word("夏天", "xiàtiān", "Summer", "Verano"),
            new Word("秋天", "qiūtiān", "Autumn; Fall", "Otoño"),
            new Word("冬天", "dōngtiān", "Winter", "Invierno"),
            new Word("天气", "tiānqì", "Weather", "Clima"),
            new Word("太阳", "tàiyáng", "Sun", "Sol"),
            new Word("月亮", "yuèliang", "Moon", "Luna"),
            new Word("星星", "xīngxing", "Star", "Estrella"),
            new Word("雨", "yǔ", "Rain", "Lluvia"),
            new Word("雪", "xuě", "Snow", "Nieve"),
            new Word("风", "fēng", "Wind", "Viento"),
            new Word("云", "yún", "Cloud", "Nube"),
            new Word("土", "tǔ", "Earth; Soil", "Tierra"),
            new Word("空气", "kōngqì", "Air", "Aire"),
            new Word("山", "shān", "Mountain", "Montaña"),
            new Word("海", "hǎi", "Sea; Ocean", "Mar; Océano"),
            new Word("树", "shù", "Tree", "Árbol"),
            new Word("花", "huā", "Flower", "Flor"),
            new Word("草", "cǎo", "Grass", "Hierba"),
            new Word("动物", "dòngwù", "Animal", "Animal"),
            new Word("狗", "gǒu", "Dog", "Perro"),
            new Word("猫", "māo", "Cat", "Gato"),
            new Word("鸟", "niǎo", "Bird", "Pájaro"),
            new Word("鱼", "yú", "Fish", "Pez"),
            new Word("马", "mǎ", "Horse", "Caballo"),
            new Word("牛", "niú", "Cow", "Vaca"),
            new Word("猪", "zhū", "Pig", "Cerdo"),
            new Word("羊", "yáng", "Sheep", "Oveja"),
            new Word("虫子", "chóngzi", "Insect; Bug", "Insecto"),
            new Word("蛇", "shé", "Snake", "Serpiente"),
            new Word("猫头鹰", "māotóuyīng", "Owl", "Búho"),
            new Word("青蛙", "qīngwā", "Frog", "Rana"),
            new Word("兔子", "tùzi", "Rabbit", "Conejo"),
            new Word("老虎", "lǎohǔ", "Tiger", "Tigre"),
            new Word("狮子", "shīzi", "Lion", "León"),
            new Word("猴子", "hóuzi", "Monkey", "Mono"),
            new Word("大象", "dàxiàng", "Elephant", "Elefante"),
            new Word("熊", "xióng", "Bear", "Oso"),
            new Word("狼", "láng", "Wolf", "Lobo"),
            new Word("狐狸", "húlí", "Fox", "Zorro"),
            new Word("海豚", "hǎitún", "Dolphin", "Delfín"),
            new Word("鲸鱼", "jīngyú", "Whale", "Ballena"),
            new Word("手机", "shǒujī", "Cell phone", "Teléfono móvil"),
            new Word("电灯", "diàndēng", "Electric light", "Lámpara eléctrica"),
            new Word("汽车", "qìchē", "Car", "Coche"),
            new Word("自行车", "zìxíngchē", "Bicycle", "Bicicleta"),
            new Word("飞机", "fēijī", "Airplane", "Avión"),
            new Word("火车", "huǒchē", "Train", "Tren"),
            new Word("船", "chuán", "Boat; Ship", "Barco"),
            new Word("商店", "shāngdiàn", "Store; Shop", "Tienda"),
            new Word("饭店", "fàndiàn", "Restaurant; Hotel", "Restaurante; Hotel"),
            new Word("银行", "yínháng", "Bank", "Banco"),
            new Word("邮局", "yóujú", "Post office", "Oficina de correos"),
            new Word("动物园", "dòngwùyuán", "Zoo", "Zoológico"),
            new Word("办公室", "bàngōngshì", "Office", "Oficina"),
            new Word("厕所", "cèsuǒ", "Bathroom; Toilet", "Baño"),
            new Word("床", "chuáng", "Bed", "Cama"),
            new Word("门", "mén", "Door", "Puerta"),
            new Word("窗户", "chuānghu", "Window", "Ventana"),
            new Word("墙", "qiáng", "Wall", "Pared"),
            new Word("灯", "dēng", "Light; Lamp", "Luz; Lámpara"),
            new Word("书", "shū", "Book", "Libro"),
            new Word("笔", "bǐ", "Pen; Pencil", "Bolígrafo; Lápiz"),
            new Word("纸", "zhǐ", "Paper", "Papel"),
            new Word("照片", "zhàopiàn", "Photograph", "Foto"),
            new Word("衣服", "yīfu", "Clothes", "Ropa"),
            new Word("鞋", "xié", "Shoes", "Zapatos"),
            new Word("帽子", "màozi", "Hat", "Sombrero"),
            new Word("手表", "shǒubiǎo", "Watch", "Reloj"),
            new Word("钱包", "qiánbāo", "Wallet", "Cartera"),
            new Word("钥匙", "yàoshi", "Key", "Llave"),
            new Word("雨伞", "yǔsǎn", "Umbrella", "Paraguas"),
            new Word("冰箱", "bīngxiāng", "Refrigerator", "Refrigerador"),
            new Word("空调", "kōngtiáo", "Air conditioner", "Aire acondicionado"),
            new Word("洗衣机", "xǐyījī", "Washing machine", "Lavadora"),
            new Word("电饭锅", "diànfànguō", "Rice cooker", "Olla arrocera"),
            new Word("钟", "zhōng", "Clock", "Reloj"),
            new Word("灯泡", "dēngpào", "Light bulb", "Bombilla"),
            new Word("学生", "xuéshēng", "Student", "Estudiante"),
            new Word("书本", "shūběn", "Book", "Libro"),
            new Word("笔记本", "bǐjìběn", "Notebook", "Cuaderno"),
            new Word("铅笔", "qiānbǐ", "Pencil", "Lápiz"),
            new Word("橡皮", "xiàngpí", "Eraser", "Goma de borrar"),
            new Word("黑板", "hēibǎn", "Blackboard", "Pizarra"),
            new Word("课本", "kèběn", "Textbook", "Libro de texto"),
            new Word("考试", "kǎoshì", "Exam", "Examen"),
            new Word("成绩", "chéngjì", "Grade; Score", "Nota; Calificación"),
            new Word("作业", "zuòyè", "Homework", "Tarea"),
            new Word("大学", "dàxué", "University", "Universidad"),
            new Word("学生证", "xuéshēng zhèng", "Student ID", "Carnet de estudiante"),
            new Word("毕业", "bìyè", "Graduation", "Graduación"),
            new Word("学历", "xué lì", "Educational background", "Formación académica"),
            new Word("学费", "xuéfèi", "Tuition fee", "Matrícula"),
            new Word("讲义", "jiǎngyì", "Lecture notes", "Apuntes"),
            new Word("实习", "shíxí", "Internship", "Prácticas"),
            new Word("研究", "yánjiū", "Research", "Investigación"),
            new Word("论文", "lùnwén", "Thesis; Paper", "Tesis; Trabajo"),
            new Word("教授", "jiàoshòu", "Professor", "Profesor universitario"),
            new Word("教科书", "jiàokēshū", "Textbook", "Libro de texto"),
            new Word("学期", "xuéqī", "Semester", "Semestre"),
            new Word("校长", "xiàozhǎng", "Principal", "Director"),
            new Word("奖学金", "jiǎngxuéjīn", "Scholarship", "Beca"),
            new Word("学生会", "xuéshēng huì", "Student union", "Asociación estudiantil"),
            new Word("自习", "zìxí", "Self-study", "Estudio autónomo"),
            new Word("答辩", "dábiàn", "Defense (thesis)", "Defensa (tesis)"),
            new Word("辅导", "fǔdǎo", "Tutoring", "Tutoría"),
            new Word("考试成绩", "kǎoshì chéngjì", "Exam results", "Resultados del examen"),
            new Word("校友", "xiàoyǒu", "Alumnus", "Exalumno"),
            new Word("学士", "xuéshì", "Bachelor's degree", "Licenciatura"),
            new Word("硕士", "shuòshì", "Master's degree", "Maestría"),
            new Word("博士", "bóshì", "Doctorate", "Doctorado"),
            new Word("班级", "bānjí", "Class", "Clase"),
            new Word("选修课", "xuǎnxiūkè", "Elective course", "Asignatura optativa"),
            new Word("必修课", "bìxiūkè", "Compulsory course", "Asignatura obligatoria"),
            new Word("校规", "xiàoguī", "School rules", "Normas escolares"),
            new Word("学位", "xuéwèi", "Academic degree", "Grado académico"),
            new Word("教学楼", "jiàoxuélóu", "Teaching building", "Edificio académico"),
            new Word("开学", "kāixué", "School starts", "Inicio de clases"),
            new Word("放学", "fàngxué", "School ends", "Fin de clases"),
            new Word("成绩单", "chéngjì dān", "Report card", "Boleta de calificaciones"),
            new Word("答题", "dá tí", "Answer questions", "Responder preguntas"),
            new Word("阅卷", "yuèjuàn", "Marking exam papers", "Corregir exámenes"),
            new Word("及格", "jígé", "Pass (an exam)", "Aprobar"),
            new Word("不及格", "bù jígé", "Fail (an exam)", "Reprobar"),
            new Word("考场", "kǎochǎng", "Examination room", "Sala de examen"),
            new Word("监考", "jiānkǎo", "Proctor", "Vigilante de examen"),
            new Word("补考", "bǔkǎo", "Make-up exam", "Examen de recuperación"),
            new Word("录取", "lùqǔ", "Admission", "Admisión"),
            new Word("学位证书", "xuéwèi zhèngshū", "Degree certificate", "Título académico"),
            new Word("校友会", "xiàoyǒu huì", "Alumni association", "Asociación de exalumnos"),
            new Word("校刊", "xiàokān", "School magazine", "Revista escolar"),
            new Word("社团", "shètuán", "Club; Society", "Club; Sociedad"),
            new Word("运动会", "yùndònghuì", "Sports meet", "Encuentro deportivo"),
            new Word("校运会", "xiàoyùnhuì", "School sports day", "Día deportivo escolar"),
            new Word("实习生", "shíxí shēng", "Intern", "Practicante"),
            new Word("导师", "dǎoshī", "Mentor", "Tutor"),
            new Word("奖项", "jiǎngxiàng", "Award", "Premio"),
            new Word("成绩优异", "chéngjì yōuyì", "Excellent grades", "Notas excelentes"),
            new Word("课程表", "kèchéng biǎo", "Class schedule", "Horario de clases"),
            new Word("校车", "xiàochē", "School bus", "Autobús escolar"),
            new Word("食堂", "shítáng", "Cafeteria", "Comedor"),
            new Word("宿舍", "sùshè", "Dormitory", "Dormitorio"),
            new Word("操场", "cāochǎng", "Playground; Sports field", "Patio; Campo deportivo"),
            new Word("讲座", "jiǎngzuò", "Lecture", "Conferencia"),
            new Word("学术", "xuéshù", "Academic", "Académico"),
            new Word("开题报告", "kāití bàogào", "Thesis proposal", "Propuesta de tesis"),
            new Word("文献", "wénxiàn", "Literature (academic)", "Literatura (académica)"),
            new Word("资料", "zīliào", "Materials; Data", "Materiales; Datos"),
            new Word("复习", "fùxí", "Review; Revise", "Repasar"),
            new Word("预习", "yùxí", "Prepare lessons", "Preparar las lecciones"),
            new Word("笔试", "bǐshì", "Written test", "Examen escrito"),
            new Word("口试", "kǒushì", "Oral test", "Examen oral"),
            new Word("作弊", "zuòbì", "Cheat (in exams)", "Hacer trampa"),
            new Word("录取", "lùqǔ", "Admission", "Admisión"),
            new Word("毕业典礼", "bìyè diǎnlǐ", "Graduation ceremony", "Ceremonia de graduación"),
            new Word("学位证书", "xuéwèi zhèngshū", "Degree certificate", "Título académico"),
            new Word("校刊", "xiàokān", "School magazine", "Revista escolar"),
            new Word("校运会", "xiàoyùnhuì", "School sports day", "Día deportivo escolar"),
            new Word("实习生", "shíxí shēng", "Intern", "Practicante"),
            new Word("导师", "dǎoshī", "Mentor", "Tutor"),
            new Word("奖项", "jiǎngxiàng", "Award", "Premio"),
            new Word("课程表", "kèchéng biǎo", "Class schedule", "Horario de clases"),
            new Word("校车", "xiàochē", "School bus", "Autobús escolar"),
            new Word("食堂", "shítáng", "Cafeteria", "Comedor"),
            new Word("宿舍", "sùshè", "Dormitory", "Dormitorio"),
            new Word("操场", "cāochǎng", "Playground; Sports field", "Patio; Campo deportivo"),
            new Word("实验室", "shíyàn shì", "Laboratory", "Laboratorio"),
            new Word("讲座", "jiǎngzuò", "Lecture", "Conferencia"),
            new Word("学术", "xuéshù", "Academic", "Académico"),
            new Word("论文答辩", "lùnwén dábiàn", "Thesis defense", "Defensa de tesis"),
            new Word("开题报告", "kāití bàogào", "Thesis proposal", "Propuesta de tesis"),
            new Word("文献", "wénxiàn", "Literature (academic)", "Literatura (académica)"),
            new Word("资料", "zīliào", "Materials; Data", "Materiales; Datos"),
            new Word("预习", "yùxí", "Prepare lessons", "Preparar las lecciones"),
            new Word("笔试", "bǐshì", "Written test", "Examen escrito"),
            new Word("口试", "kǒushì", "Oral test", "Examen oral"),
            new Word("学习方法", "xuéxí fāngfǎ", "Study method", "Método de estudio"),
            new Word("优点", "yōudiǎn", "Strength; Advantage", "Punto fuerte; ventaja"),
            new Word("缺点", "quēdiǎn", "Weakness; Disadvantage", "Debilidad; desventaja"),
            new Word("专注", "zhuānzhù", "Focus", "Concentración"),
            new Word("时间管理", "shíjiān guǎnlǐ", "Time management", "Gestión del tiempo"),
            new Word("笔记", "bǐjì", "Notes", "Apuntes"),
            new Word("学生", "xuéshēng", "Student", "Estudiante"),
            new Word("考试压力", "kǎoshì yālì", "Exam pressure", "Presión de exámenes"),
            new Word("自习", "zìxí", "Self-study", "Estudio independiente"),
            new Word("学习计划", "xuéxí jìhuà", "Study plan", "Plan de estudio"),
            new Word("辅导班", "fǔdǎo bān", "Tutoring class", "Clase de apoyo"),
            new Word("写作", "xiězuò", "Writing", "Escritura"),
            new Word("阅读", "yuèdú", "Reading", "Lectura"),
            new Word("听力", "tīnglì", "Listening", "Comprensión auditiva"),
            new Word("口语", "kǒuyǔ", "Speaking", "Expresión oral"),
            new Word("考试技巧", "kǎoshì jìqiǎo", "Exam techniques", "Técnicas de examen"),
            new Word("紧张", "jǐnzhāng", "Nervous", "Nervioso"),
            new Word("放松", "fàngsōng", "Relax", "Relajarse"),
            new Word("努力", "nǔlì", "Work hard", "Esforzarse"),
            new Word("毕业", "bìyè", "Graduate", "Graduarse"),
            new Word("录取通知书", "lùqǔ tōngzhīshū", "Admission letter", "Carta de admisión"),
            new Word("左边", "zuǒbiān", "Left side", "Lado izquierdo"),
            new Word("右边", "yòubiān", "Right side", "Lado derecho"),
            new Word("前面", "qiánmiàn", "Front; In front", "Delante"),
            new Word("后面", "hòumiàn", "Back; Behind", "Detrás"),
            new Word("上面", "shàngmiàn", "Above; On top", "Encima"),
            new Word("下面", "xiàmiàn", "Below; Under", "Debajo"),
            new Word("里面", "lǐmiàn", "Inside", "Dentro"),
            new Word("外面", "wàimiàn", "Outside", "Fuera"),
            new Word("附近", "fùjìn", "Nearby", "Cerca"),
            new Word("国家", "guójiā", "Country", "País"),
            new Word("中间", "zhōngjiān", "Middle; Center", "En medio"),
            new Word("中国", "Zhōngguó", "China", "China"),
            new Word("美国", "Měiguó", "United States", "Estados Unidos"),
            new Word("西班牙", "Xībānyá", "Spain", "España"),
            new Word("法国", "Fǎguó", "France", "Francia"),
            new Word("日本", "Rìběn", "Japan", "Japón"),
            new Word("德国", "Déguó", "Germany", "Alemania"),
            new Word("英国", "Yīngguó", "United Kingdom", "Reino Unido"),
            new Word("加拿大", "Jiānádà", "Canada", "Canadá"),
            new Word("意大利", "Yìdàlì", "Italy", "Italia"),
            new Word("巴西", "Bāxī", "Brazil", "Brasil"),
            new Word("澳大利亚", "Àodàlìyà", "Australia", "Australia"),
            new Word("树", "shù", "Tree", "Árbol"),
            new Word("花", "huā", "Flower", "Flor"),
            new Word("草", "cǎo", "Grass", "Hierba"),
            new Word("山", "shān", "Mountain", "Montaña"),
            new Word("河", "hé", "River", "Río"),
            new Word("湖", "hú", "Lake", "Lago"),
            new Word("海", "hǎi", "Sea", "Mar"),
            new Word("天空", "tiānkōng", "Sky", "Cielo"),
            new Word("云", "yún", "Cloud", "Nube"),
            new Word("风", "fēng", "Wind", "Viento"),
            new Word("太阳", "tàiyáng", "Sun", "Sol"),
            new Word("月亮", "yuèliang", "Moon", "Luna"),
            new Word("饭", "fàn", "Meal; Cooked rice", "Comida; arroz cocido"),
            new Word("车", "chē", "Car; Vehicle", "Coche; vehículo"),
            new Word("朋友", "péngyǒu", "Friend", "Amigo"),
            new Word("工作", "gōngzuò", "Work; Job", "Trabajo"),
            new Word("时间", "shíjiān", "Time", "Tiempo"),
            new Word("学校", "xuéxiào", "School", "Escuela"),
            new Word("书", "shū", "Book", "Libro"),
            new Word("门", "mén", "Door", "Puerta"),
            new Word("窗户", "chuānghù", "Window", "Ventana"),
            new Word("灯", "dēng", "Light; Lamp", "Luz; lámpara"),
            new Word("床", "chuáng", "Bed", "Cama"),
            new Word("衣服", "yīfú", "Clothes", "Ropa"),
            new Word("鞋子", "xiézi", "Shoes", "Zapatos"),
            new Word("包", "bāo", "Bag", "Bolso; mochila"),
            new Word("钱", "qián", "Money", "Dinero"),
            new Word("钥匙", "yàoshi", "Key", "Llave"),
            new Word("电视", "diànshì", "Television; TV", "Televisión"),
            new Word("冰箱", "bīngxiāng", "Refrigerator", "Nevera"),
            new Word("厨房", "chúfáng", "Kitchen", "Cocina"),
            new Word("厕所", "cèsuǒ", "Toilet", "Baño"),
            new Word("水杯", "shuǐbēi", "Water cup; glass", "Vaso de agua"),
            new Word("笔", "bǐ", "Pen", "Bolígrafo"),
            new Word("纸", "zhǐ", "Paper", "Papel"),
            new Word("朋友", "péngyǒu", "Friend", "Amigo"),
            new Word("家人", "jiārén", "Family member", "Familiar"),
            new Word("孩子", "háizi", "Child", "Niño"),
            new Word("老师", "lǎoshī", "Teacher", "Profesor"),
            new Word("学生", "xuéshēng", "Student", "Estudiante"),
            new Word("街道", "jiēdào", "Street", "Calle"),
            new Word("商店", "shāngdiàn", "Shop", "Tienda"),
            new Word("医生", "yīshēng", "Doctor", "Médico"),
            new Word("医院", "yīyuàn", "Hospital", "Hospital"),
            new Word("朋友", "péngyǒu", "Friend", "Amigo"),
            new Word("家", "jiā", "Home", "Casa"),
            new Word("电话", "diànhuà", "Telephone", "Teléfono"),
            new Word("电脑", "diànnǎo", "Computer", "Ordenador; Computadora"),
            new Word("书", "shū", "Book", "Libro"),
            new Word("笔", "bǐ", "Pen", "Bolígrafo"),
            new Word("纸", "zhǐ", "Paper", "Papel"),
            new Word("窗户", "chuānghù", "Window", "Ventana"),
            new Word("门", "mén", "Door", "Puerta"),
            new Word("椅子", "yǐzi", "Chair", "Silla"),
            new Word("衣服", "yīfu", "Clothes", "Ropa"),
            new Word("鞋子", "xiézi", "Shoes", "Zapatos"),
            new Word("钱", "qián", "Money", "Dinero"),
            new Word("时间", "shíjiān", "Time", "Tiempo"),
            new Word("天气", "tiānqì", "Weather", "Clima"),
            new Word("早上", "zǎoshang", "Morning", "Mañana"),
            new Word("晚上", "wǎnshang", "Evening", "Noche"),
            new Word("星期", "xīngqī", "Week", "Semana"),
            new Word("月", "yuè", "Month", "Mes"),
            new Word("年", "nián", "Year", "Año"),
            new Word("火", "huǒ", "Fire", "Fuego"),
            new Word("电", "diàn", "Electricity", "Electricidad"),
            new Word("电话", "diànhuà", "Phone", "Teléfono"),  // repetida, la quito
            new Word("公园", "gōngyuán", "Park", "Parque"),
            new Word("桥", "qiáo", "Bridge", "Puente"),
            new Word("市场", "shìchǎng", "Market", "Mercado"),
            new Word("语言", "yǔyán", "Language", "Idioma"),
            new Word("一个", "yīgè", "One", "Uno"),
            new Word("喝茶", "hēchá", "Drink tea", "Beber té"),
            new Word("常常", "chángcháng", "Often", "A menudo"),
            new Word("一起", "yīqǐ", "Together", "Juntos"),
            new Word("去", "qù", "Go", "Ir"),
            new Word("这个", "zhège", "This", "Este"),
            new Word("星期天", "xīngqītiān", "Sunday", "Domingo"),
            new Word("想", "xiǎng", "Want", "Querer"),
            new Word("去", "qù", "Go", "Ir"),
            new Word("看", "kàn", "Watch", "Ver"),
            new Word("吗", "ma", "Question particle", "Partícula interrogativa(¿?)"),
            new Word("快乐", "kuàilè", "Happy", "Feliz"),
            new Word("然后", "rán hòu", "Then", "Luego; Entonces"),
            new Word("吃", "chī", "To eat", "Comer"),
            new Word("也", "yě", "Also", "También"),
            new Word("每天", "měitiān", "Every day", "Cada día"),
            new Word("早上", "zǎoshàng", "Morning", "Mañana"),
            new Word("七", "qī", "Seven", "Siete"),
            new Word("点", "diǎn", "O'clock", "Hora"),
            new Word("起床", "qǐchuáng", "Get up", "Levantarse"),
            new Word("吃", "chī", "Eat", "Comer"),
            new Word("早饭", "zǎofàn", "Breakfast", "Desayuno"),
            new Word("然后", "ránhòu", "Then", "Luego"),
            new Word("去", "qù", "Go", "Ir"),
            new Word("学校", "xuéxiào", "School", "Escuela"),
            new Word("老师", "lǎoshī", "Teacher", "Profesor/a"),
            new Word("在", "zài", "At", "En"),
            new Word("教室", "jiàoshì", "Classroom", "Aula"),
            new Word("等", "děng", "Wait", "Esperar"),
            new Word("我们", "wǒmen", "We", "Nosotros"),
            new Word("中午", "zhōngwǔ", "Noon", "Mediodía"),
            new Word("一起", "yīqǐ", "Together", "Juntos"),
            new Word("作业", "zuòyè", "Homework", "Tarea"),
            new Word("听", "tīng", "Listen", "Escuchar"),
            new Word("音乐", "yīnyuè", "Music", "Música"),
            new Word("晚上", "wǎnshàng", "Evening", "Noche"),
            new Word("看", "kàn", "Watch", "Ver"),
            new Word("电视", "diànshì", "Television", "Televisión"),
            new Word("很", "hěn", "Very", "Muy"),
            new Word("开心", "kāixīn", "Happy", "Feliz"),
            new Word("昨天", "zuótiān", "Yesterday", "Ayer"),
            new Word("和", "hé", "And", "Y"),
            new Word("去", "qù", "Go", "Ir"),
            new Word("商店", "shāngdiàn", "Store", "Tienda"),
            new Word("一件", "yījiàn", "One piece", "Una prenda"),
            new Word("新", "xīn", "New", "Nuevo/a"),
            new Word("一本", "yīběn", "One book", "Un libro"),
            new Word("先", "xiān", "First", "Primero"),
            new Word("坐", "zuò", "Sit", "Sentarse"),
            new Word("地铁", "dìtiě", "Subway", "Metro"),
            new Word("走路", "zǒulù", "Walk", "Caminar"),
            new Word("里", "lǐ", "Inside", "Dentro"),
            new Word("很多", "hěn duō", "Many", "Muchos"),
            new Word("人", "rén", "People", "Gente; Persona"),
            new Word("等", "děng", "Wait", "Esperar"),
            new Word("了", "le", "Past particle", "Partícula de pasado"),
            new Word("很", "hěn", "Very", "Muy"),
            new Word("久", "jiǔ", "Long", "Largo"),
            new Word("最后", "zuìhòu", "Finally", "Finalmente"),
            new Word("两本", "liǎng běn", "Two books", "Dos libros"),
            new Word("买到", "mǎidào", "Bought", "Comprar y conseguir"),
            new Word("喜欢", "xǐhuān", "Like", "Gustar"),
            new Word("都", "dōu", "All", "Todos"),
            new Word("高兴", "gāoxìng", "Happy", "Feliz"),
            new Word("李明", "Lǐ Míng", "Li Ming", "Li Ming"),
            new Word("最近", "zuìjìn", "Recently", "Recientemente"),
            new Word("开始", "kāishǐ", "Start", "Empezar"),
            new Word("学习", "xuéxí", "Study", "Estudiar"),
            new Word("做饭", "zuòfàn", "Cook", "Cocinar"),
            new Word("他", "tā", "He", "Él"),
            new Word("每天", "měitiān", "Every day", "Cada día"),
            new Word("晚上", "wǎnshàng", "Evening", "Noche"),
            new Word("看", "kàn", "Watch", "Ver"),
            new Word("一个", "yīgè", "One", "Uno"),
            new Word("教学", "jiàoxué", "Teaching", "Enseñanza"),
            new Word("视频", "shìpín", "Video", "Video"),
            new Word("然后", "ránhòu", "Then", "Luego"),
            new Word("试着", "shìzhe", "Try", "Intentar"),
            new Word("做", "zuò", "Do", "Hacer"),
            new Word("一样", "yīyàng", "Same", "Mismo"),
            new Word("菜", "cài", "Dish", "Plato"),
            new Word("刚", "gāng", "Just", "Justo"),
            new Word("开始", "kāishǐ", "Start", "Comenzar"),
            new Word("的时候", "de shíhòu", "When", "Cuando"),
            new Word("总是", "zǒngshì", "Always", "Siempre"),
            new Word("忘记", "wàngjì", "Forget", "Olvidar"),
            new Word("放", "fàng", "Put", "Poner"),
            new Word("盐", "yán", "Salt", "Sal"),
            new Word("或者", "huòzhě", "Or", "O"),
            new Word("太多", "tài duō", "Too much", "Demasiado"),
            new Word("水", "shuǐ", "Water", "Agua"),
            new Word("后来", "hòulái", "Later", "Después"),
            new Word("慢慢地", "mànmàn de", "Slowly", "Poco a poco"),
            new Word("学会", "xuéhuì", "Learn", "Aprender"),
            new Word("怎么", "zěnme", "How", "Cómo"),
            new Word("准备", "zhǔnbèi", "Prepare", "Preparar"),
            new Word("材料", "cáiliào", "Ingredients", "Ingredientes"),
            new Word("掌握", "zhǎngwò", "Master", "Dominar"),
            new Word("火候", "huǒhòu", "Heat", "Tiempo de cocción"),
            new Word("现在", "xiànzài", "Now", "Ahora"),
            new Word("已经", "yǐjīng", "Already", "Ya"),
            new Word("可以", "kěyǐ", "Can", "Poder"),
            new Word("几个", "jǐ gè", "A few", "Algunos"),
            new Word("简单", "jiǎndān", "Simple", "Sencillo"),
            new Word("比如", "bǐrú", "For example", "Por ejemplo"),
            new Word("炒鸡蛋", "chǎo jīdàn", "Scrambled eggs", "Huevo revuelto"),
            new Word("炒面", "chǎo miàn", "Fried noodles", "Fideos fritos"),
            new Word("青菜", "qīngcài", "Vegetables", "Verduras"),
            new Word("家人", "jiārén", "Family", "Familia"),
            new Word("都", "dōu", "All", "Todos"),
            new Word("说", "shuō", "Say", "Decir"),
            new Word("进步", "jìnbù", "Progress", "Progreso"),
            new Word("很快", "hěn kuài", "Quickly", "Rápido"),
            new Word("上周末", "shàng zhōumò", "Last weekend", "El fin de semana pasado"),
            new Word("还", "hái", "Still", "Aún"),
            new Word("请", "qǐng", "Invite", "Invitar"),
            new Word("朋友", "péngyǒu", "Friend", "Amigo"),
            new Word("来", "lái", "Come", "Venir"),
            new Word("家里", "jiālǐ", "Home", "Casa"),
            new Word("吃饭", "chīfàn", "Eat", "Comer"),
            new Word("大家", "dàjiā", "Everyone", "Todos"),
            new Word("很好", "hěn hǎo", "Very good", "Muy bien"),
            new Word("感到", "gǎndào", "Feel", "Sentir"),
            new Word("非常", "fēicháng", "Very", "Muy"),
            new Word("不", "bù", "Not", "No"),
            new Word("。", "。", "Period", "Punto"),
            new Word("，", "，", "Comma", "Coma"),
            new Word("所以", "suǒyǐ", "So", "Por lo tanto"),
            new Word("虽然", "suīrán", "Although", "Aunque"),
            new Word("但是", "dànshì", "But", "Pero"),
            new Word("但", "dàn", "But", "Pero"),
            new Word("？", "？", "Question mark", "Signo de interrogación"),
            new Word("。。。", "。。。", "Ellipsis", "Elipsis"),
            new Word("每天晚上", "měitiān wǎnshàng", "Every evening", "Cada noche"),
            new Word("时候", "shíhòu", "Time", "Momento"),
            new Word("放盐", "fàng yán", "Put salt", "Poner sal"),
            new Word("放太多水", "fàng tài duō shuǐ", "Put too much water", "Poner demasiada agua"),
            new Word("慢慢", "mànmàn", "Slowly", "Poco a poco"),
            new Word("地", "de", "Particle", "Partícula de adverbio"),
            new Word("们", "men", "Plural marker for people", "Sufijo plural para personas"),
            new Word("好吃", "hǎochī", "Delicious", "Delicioso"),
            new Word("做作业", "zuò zuòyè", "Do homework", "Hacer tarea"),
            new Word("七点", "qī diǎn", "Seven o'clock", "Siete en punto"),
            new Word("看电视", "kàn diànshì", "Watch TV", "Ver televisión"),
            new Word("看书", "kàn shū", "Read a book", "Leer un libro"),
            new Word("住在一起", "zhù zài yīqǐ", "Live together", "Vivir juntos"),
            new Word("两本书", "liǎng běn shū", "Two books", "Dos libros"),
        };

        for(int i=0; i<words.length; i++){
            dictionaryService.save(words[i]);
        }

        Text[] texts = new Text[]{                  //Hay que generar los objetos
            new Text(
                "My good friend",
                "Mi buena amiga",
                "我有一个朋友。她喜欢喝茶，也喜欢看书。我们常常一起去公园。",
                "I have a friend. She likes to drink tea and also read books. We often go to the park together.",
                "Tengo una amiga. A ella le gusta tomar té y también leer libros. A menudo vamos juntas al parque.",
                "A text about my friend",
                "Un texto sobre mi amiga",
                "HSK1",
                LocalDate.of(2025, 5, 30),
                null // imagen
            ),
            new Text(
                "I'm free on Sunday",
                "Este domingo estoy libre",
                "这个星期天我不工作。我想去看电影，然后吃中国菜。你想一起去吗?",
                "This Sunday I'm not working. I want to go to the movies and then eat Chinese food. Do you want to go with me?",
                "Este domingo no trabajo. Quiero ir al cine y luego comer comida china. ¿Quieres ir conmigo?",
                "Everyone enjoys a day off work. What about you? What do you do when you don't have to work?",
                "Todo el mundo disfruta de un domingo sin trabajo, ¿y tú, qué haces los días que no trabajas?",
                "HSK1",
                LocalDate.of(2025, 5, 31),
                null // imagen
            ),
            new Text(
                "My home",
                "Mi casa",
                "我有一个家。爸爸、妈妈和我住在一起。我们很快乐。",
                "I have a home. Dad, mom, and I live together. We are very happy.",
                "Tengo una familia. Papá, mamá y yo vivimos juntos. Somos muy felices.",
                "A text about my friend",
                "Un texto sobre mi amiga",
                "HSK1",
                LocalDate.of(2025, 5, 27),
                null // imagen
            ),
            new Text(
                "Daily routine",
                "Rutina diaria",
                "我每天早上七点起床。我吃早饭，然后去学校。老师在教室等我们。中午我们一起吃饭。下午我做作业，听音乐。晚上我看电视，很开心。",
                "I get up at seven every morning. I eat breakfast, then go to school. The teacher waits for us in the classroom. At noon we eat together. In the afternoon I do homework and listen to music. In the evening I watch TV and feel very happy.",
                "Me levanto a las siete cada mañana. Desayuno, luego voy a la escuela. El profesor nos espera en el aula. Al mediodía comemos juntos. Por la tarde hago la tarea y escucho música. Por la noche veo televisión y estoy muy feliz.",
                "What an exhausting day!",
                "Demasiado trabajo por hoy",
                "HSK2",
                LocalDate.of(2025, 5, 27),
                null // imagen
            ),
            new Text(
                "Shopping with my mom",
                "De compras con mi madre",
                "昨天我和妈妈去商店。她想买一件新衣服，我想买一本书。我们先坐地铁，然后走路。商店里有很多人，我们等了很久。最后，我买了两本书，妈妈也买到了她喜欢的衣服。我们都很高兴。",
                "Yesterday I went to the store with my mom. She wanted to buy new clothes, and I wanted to buy a book. First, we took the subway, then walked. There were many people in the store; we waited for a long time. In the end, I bought two books, and my mom also got the clothes she liked. We were both very happy.",
                "Ayer fui a la tienda con mi mamá. Ella quería comprar ropa nueva, y yo quería comprar un libro. Primero tomamos el metro y luego caminamos. Había mucha gente en la tienda; esperamos mucho tiempo. Al final, compré dos libros y mi mamá también consiguió la ropa que le gustaba. Estábamos muy contentas.",
                "Mary and her mom went shopping. Do you dare to go with them?",
                "María y su madre fueron a comprar juntas. ¿Te atreves a ir con ellas?",
                "HSK2",
                LocalDate.of(2025, 5, 30),
                null // imagen
            ),
            new Text(
                "Li Ming is a chef!",
                "¡Li Ming ya es chef!",
                "李明最近开始学习做饭。他每天晚上看一个教学视频，然后试着做一样的菜。刚开始的时候，他总是忘记放盐或者放太多水。后来，他慢慢地学会了怎么准备材料，怎么掌握火候。现在，他已经可以做几个简单的菜了，比如炒鸡蛋、炒面和青菜。他的家人都说他进步很快。上周末，他还请朋友们来家里吃饭。大家都说菜很好吃，他感到非常开心。",
                "Recently, Li Ming started learning how to cook. Every evening, he watches a tutorial video and then tries to make the same dish. At first, he always forgot to add salt or used too much water. Later, he gradually learned how to prepare ingredients and control the heat. Now, he can already cook a few simple dishes, like scrambled eggs, fried noodles, and vegetables. His family says he has improved a lot. Last weekend, he even invited his friends over for dinner. Everyone said the food was delicious, and he felt very happy.",
                "Últimamente, Li Ming ha empezado a aprender a cocinar. Cada noche ve un video de enseñanza y luego intenta preparar el mismo plato. Al principio, siempre se le olvidaba poner sal o usaba demasiada agua. Después, poco a poco aprendió a preparar los ingredientes y a controlar el fuego. Ahora ya puede hacer algunos platos sencillos, como huevos revueltos, fideos fritos y verduras. Su familia dice que ha mejorado mucho. El fin de semana pasado, incluso invitó a sus amigos a cenar en casa. Todos dijeron que la comida estaba muy rica, y él se sintió muy feliz.",
                "A text about my friend",
                "Un texto sobre mi amiga",
                "HSK3",
                LocalDate.of(2025, 5, 30),
                null // imagen
            ),
        };

        String[] images = new String[]{
            "/static/images/two_good_friends.png",
            "/static/images/free_on_sunday.png",
            "/static/images/my_home.png",
            "/static/images/daily_routine.jpg",
            "/static/images/de_compras_con_mi_madre.png",
            "/static/images/li_ming_chef.jpg"
        };

        for(int i=0; i<texts.length; i++){          //Establecemos las imagenes y guardamos los textos
            try {
                this.setImage(texts[i], images[i]);
                textService.save(texts[i]);
            } catch (IOException e){
                System.err.println("Error processing text at index " + i + ": " + e.getMessage());
                e.printStackTrace(); // Opcional: para ver la traza del error
            }
        }

        User[] users = new User[]{
            new User("victorgarciallorente15@gmail.com", "JV", passwordEncoder.encode("1234"), "es", "USER"),
            new User("victorgarciallorente20@gmail.com", "J. Victor Garcia Llorente", passwordEncoder.encode("1234"), "es", "ADMIN")
        };

        for(int i=0; i<users.length; i++){
            userService.save(users[i]);
        }

        Collection[] collections = new Collection[] { 
            new Collection("Adjectives HSK1", 
            LocalDate.of(2025, 5, 27), 
            users[0],
            null
            ),
            new Collection("Nouns HSK3",
            LocalDate.of(2025, 4, 3),
            users[0],
            null
            )                              
        };

        for(int i=0; i<collections.length; i++){
            collectionService.save(collections[i]);
        }

        Flashcard flashcard1 = new Flashcard(words[0], texts[0], collections[1]);
        Flashcard flashcard2 = new Flashcard(words[1], texts[1], collections[0]);
        Flashcard flashcard3 = new Flashcard(words[2], texts[5], collections[1]);
        Flashcard flashcard4 = new Flashcard(words[4], texts[2], collections[1]);

        flashcardService.save(flashcard1);
        flashcardService.save(flashcard2);
        flashcardService.save(flashcard3);
        flashcardService.save(flashcard4);

    }

    private void setImage(Text text, String classpathResource) throws IOException {
		Resource image = new ClassPathResource(classpathResource);
		text.setImage(BlobProxy.generateProxy(image.getInputStream(), image.contentLength()));
	}
}
